version: '3'
services:
  gateway:
    build: .
    privileged: true
    ports:
      - "8080:8080"
    networks:
      - redis-net
    links:
      - "rate-limiter:rate-limiter"
    environment:
      - API_URL=http://rate-limiter:8085

  rate-limiter:
    build: ./golang-redis-rate-limiter
    privileged: true
    ports:
      - "8085:8085"
    networks:
      - redis-net
    volumes:
      - ./golang-redis-rate-limiter/app/init.go:/go/src/github.com/shredx/golang-redis-rate-limiter/app/init.go
      - ./golang-redis-rate-limiter/app/models:/go/src/github.com/shredx/golang-redis-rate-limiter/app/models
      - ./golang-redis-rate-limiter/app/controllers:/go/src/github.com/shredx/golang-redis-rate-limiter/app/controllers
      - ./golang-redis-rate-limiter/app/views:/go/src/github.com/shredx/golang-redis-rate-limiter/app/views
      - ./golang-redis-rate-limiter/conf:/go/src/github.com/shredx/golang-redis-rate-limiter/conf

  node-token-generator:
    build: ./node-redis-rate-limiter
    privileged: true
    ports:
      - "9090:9090"
    networks:
      - redis-net
    links:
      - redis:redis
    environment:
      - REDIS_URL=redis://redis:6379
      - PORT=9090
      - TOKEN_SECRET=well-its-not-that-secure
      - ACCESS_TOKEN_EXPIRY=10h
      - ACCESS_TOKEN_ALGO=HS256
      - REFRESH_TOKEN_EXPIRY=9h
      - REFRESH_TOKEN_ALGO=HS256

  redis:
    hostname: redis
    image: redis
    networks:
      - redis-net

  nginx:
    build: ./final-build
    links:
      - "rate-limiter:rate-limiter"
      - "gateway:api-gateway"
      - "node-token-generator:token-generator"
    ports:
      - "8081:80"
    networks:
      - redis-net

      
networks:
  redis-net:
    driver: bridge
